### ISSUE TITLE
Support "uuid" type

### ISSUE THREAD

**Issue by tvogels01** [harrystech/arthur-redshift-etl#338]
We should explicitly call out when an upstream table or a transformation has a `uuid` column.
For upstream, this would allow us to enable partitioning by that column.

For now, the expectation is:
1. Add new `type` of `uuid` to the schema for table designs.
2. When upstream shows a `uuid` column, then assign that `type` automatically.

**Comment by thomas-vogels** [comment]
This is now supported with something like this:
```
        {
            "name": "public_id",
            "sql_type": "varchar(36)",
            "type": "uuid",
            "expression": "\"public_id\"::varchar(36)",
            "source_sql_type": "uuid"
        },
```
