### ISSUE TITLE
Can't identify final extract failures in monitor payloads

### ISSUE THREAD

**Issue by bhtucker** [harrystech/arthur-redshift-etl#72]
In terms of output what is recorded by the monitor, failures that will be retried look like final failures.

This poses a problem for concurrent load — load thinks the first failure it sees is final. Since the extract job might have different settings than load, you can't know based on the `attempt_num` if this is the final one.

**Comment by tvogels01** [comment]
I'm closing this for now.  The retries are no longer recorded in the events table so skipping past to the last event doesn't matter. Unfortunately we now have also lost the opportunity to see in the events table whether retries have occurred.
